<?xml version="1.0"?>
<package format="3">
  <name>trail</name>
  <version>0.1.0</version>         
  <description>TRaIL-Odom: Tightly Coupled Continuous Time Radar-IMU-LiDAR Odometry with Adaptive Doppler Weighting</description>

  <maintainer email="gch06208@snu.ac.kr">Chiyun Noh</maintainer>
  <author>Chiyun Noh</author>
  <author>Turcan Tuna</author>
  <author>William Talbot</author>
  <author>Marco Hutter</author>
  <author>Laurent Kneip</author>
  <author>Ayoung Kim</author>
  <license>MIT</license>         

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>

  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>

  <depend>rosbag2_cpp</depend>

  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
